var schools = [
    { 'person': '曹锐', 'school': '香港大学', 'major': '工学院' },
    { 'person': '陈钶 ker', 'school': '温州医科大学', 'major': '' },
    { 'person': '陈世君', 'school': '多伦多大学', 'major': '' },
    { 'person': '陈润澎', 'school': '杭州电子科技大学', 'major': ''},
    { 'person': '付李想', 'school': '吉林大学', 'major': '' },
    { 'person': '何元捷', 'school': '深圳大学', 'major': '' },
    { 'person': '李谞远', 'school': '浙江大学', 'major': '' },
    { 'person': '李思涵', 'school': '杭州电子科技大学', 'major': '' },
    { 'person': '徐嘉浩', 'school': '武汉大学', 'major': '' },
    { 'person': '何雨晴', 'school': '西北工业大学明德学院', 'major': '' },
    { 'person': '蒋霆龙', 'school': '浙江工业大学', 'major': '土木工程（中外合作办学）' },
    { 'person': '林银燕', 'school': '浙江工业大学', 'major': '' },
    { 'person': '凌瑞添', 'school': '东北大学秦皇岛分校', 'major': '机械类' },
    { 'person': '罗　迈', 'school': '伦敦大学学院', 'major': '艺术学院' },
    { 'person': '罗浩天', 'school': '浙江海洋大学', 'major': '轮机工程' },
    { 'person': '吕宏波', 'school': '浙江万里学院', 'major': '' },
    { 'person': '吕思佳', 'school': '大连海事大学', 'major': '' },
    { 'person': '邵琪雅', 'school': '杭州电子科技大学', 'major': '会计类' },
    { 'person': '沈汝奕', 'school': '浙江理工大学', 'major': '' },
    { 'person': '宋　琳', 'school': '浙江传媒学院', 'major': '数字媒体技术' },
    { 'person': '宋珂源', 'school': '哈尔滨工业大学', 'major': '工科试验班(计算机与电子通信)' },
    { 'person': '王　懿', 'school': '浙江农林大学', 'major': '' },
    { 'person': '王程可', 'school': '浙江工商大学', 'major': '电子信息类' },
    { 'person': '谢易作', 'school': '浙江警官职业学院', 'major': '' },
    { 'person': '徐艳琪', 'school': '西南交通大学', 'major': '' },
    { 'person': '严梦柯', 'school': '宁波工程学院风华校区', 'major': '' },
    { 'person': '颜祺淞', 'school': '杭州电子科技大学', 'major': '电子信息类（三位一体）' },
    { 'person': '杨　柳', 'school': '浙江工商大学', 'major': '计算机专业' },
    { 'person': '叶相湾', 'school': '兰州理工大学', 'major': '金属材料工程' },
    { 'person': '应波波', 'school': '安徽大学', 'major': '德语系' },
    { 'person': '张晨昱', 'school': '长安大学', 'major': '' },
    { 'person': '张佳宁', 'school': '浙江农林大学', 'major': '计算机科学与技术（三位一体）' },
    { 'person': '张靖赟', 'school': '北京航空航天大学', 'major': '工科试验班类(信息类)' },
    { 'person': '章楷豪', 'school': '西安电子科技大学', 'major': '电子信息类(物理与光电工程)' },
    { 'person': '郑成锴', 'school': '四川农业大学成都校区', 'major': '' },
    { 'person': '郑虞颖', 'school': '宁波大学', 'major': '数学与应用数学' },
    { 'person': '钟江涛', 'school': '温州医科大学', 'major': '临床医学' },
    { 'person': '朱天渝', 'school': '南京邮电大学', 'major': '材料化学' }
];